#Instalação do Pandas

In [110]:
# Instalando a biblioteca Pandas
!pip install pandas

# Instalando uma versão especifica da biblioteca
# !pip install pandas==2.2.2

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [111]:
import pandas as pd
import numpy as np

print('Versão Numpy ' + np.__version__) # Verificando a versão do NumPy
print('Versão Pandas ' + pd.__version__) # Verificando a versão do Pandas

Versão Numpy 2.1.3
Versão Pandas 2.2.3

# Series
- Documentação: https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series

In [112]:
series_dados = pd.Series([10,20,30,40,50]) # Criando uma Series com valores
print(series_dados)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [113]:
type(series_dados) # Verificando o tipo de dados da função

pandas.core.series.Series

In [114]:
array_inteiros = (10,20,30,40,50) # Criando uma Array
indices = ('a', 'b', 'c', 'd', 'e') # Criando índices

serie_dados = pd.Series(array_inteiros, index=indices) # Pegando o Array e o índice e transformando em uma Series
print(serie_dados)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [115]:
np_array_inteiros = np.array([10,20,50,40,50]) # Criando um Array em NumPy
print(np_array_inteiros)

[10 20 50 40 50]

In [116]:
type(np_array_inteiros)

numpy.ndarray

In [117]:
serie_dados =pd.Series(np_array_inteiros) # Convertendo o Array da NumPy para uma Series no Pandas, com indices.
print(serie_dados)

0    10
1    20
2    50
3    40
4    50
dtype: int64

In [118]:
serie_dados.shape # Mais util para DataFrames, verificar o formato.

(5,)

In [119]:
series_dados.ndim # Contagem das Dimensões

1

In [120]:
serie_dados.size # Contagem da quantidade de elementos

5

In [121]:
serie_dados.index = ['A','T','A','C','K',] # Modificando os índices das Series
print(serie_dados)

A    10
T    20
A    50
C    40
K    50
dtype: int64

In [122]:
valores = np.random.random(10) # Criando valores aleatorios com NumPy
indexes = np.arange(0,10)      # Definindo índices conforme a quantidade de números no Array

print(valores)
print(indexes)

[0.42594191 0.780253   0.02293072 0.56541289 0.59219733 0.33058136
 0.57823396 0.62511047 0.92703497 0.56997704]
[0 1 2 3 4 5 6 7 8 9]

In [123]:
type(valores), type(indexes)

(numpy.ndarray, numpy.ndarray)

In [124]:
sequencia_de_valores = pd.Series(valores, index=indexes) # Convertendo o Array e Índice em Series
print(sequencia_de_valores)

0    0.425942
1    0.780253
2    0.022931
3    0.565413
4    0.592197
5    0.330581
6    0.578234
7    0.625110
8    0.927035
9    0.569977
dtype: float64

In [125]:
sequencia_de_valores.index # Somente os índices

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [126]:
dick = {'Joao': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9} # Criando um dicionario
type(dick)

dict

In [127]:
dick

{'Joao': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}

In [128]:
dict_serie_dados = pd.Series(dick)
print(dict_serie_dados)

Joao       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [129]:
dict_serie_dados.dtype

dtype('int64')

# Fatiamento (Slicing)

In [130]:
sequencia_de_valores[:] # Abrindo e fechando colchetes, podemos indicar os indices que irão retornar

0    0.425942
1    0.780253
2    0.022931
3    0.565413
4    0.592197
5    0.330581
6    0.578234
7    0.625110
8    0.927035
9    0.569977
dtype: float64

In [131]:
sequencia_de_valores[:3] # Aqui podemos pontuar o inicio e o fim para nos retornar. Podendo deixar [:3] ou [0:3] o próprio pandas reconhece a linha inicial

0    0.425942
1    0.780253
2    0.022931
dtype: float64

In [132]:
sequencia_de_valores[-1:] # Obtendo somente o último valor que está armazenado

9    0.569977
dtype: float64

In [133]:
sequencia_de_valores[:-1] # Excluindo o ultimo registro da Serie

0    0.425942
1    0.780253
2    0.022931
3    0.565413
4    0.592197
5    0.330581
6    0.578234
7    0.625110
8    0.927035
dtype: float64

In [134]:
big_dick = sequencia_de_valores[:3]
print(big_dick)

0    0.425942
1    0.780253
2    0.022931
dtype: float64

# Cópia, Conversão e Concatenação
- copy()
- astype()
- pd.concat([])

In [135]:
serie_dados = sequencia_de_valores.copy() # Fazendo uma cópia de Serie
print(serie_dados)

0    0.425942
1    0.780253
2    0.022931
3    0.565413
4    0.592197
5    0.330581
6    0.578234
7    0.625110
8    0.927035
9    0.569977
dtype: float64

In [136]:
serie_dados.dtype

dtype('float64')

In [137]:
sd = serie_dados.astype(int) # Alterando o tipo das Serie, nesse caso de Float para Int

In [138]:
sd.dtype

dtype('int64')

In [139]:
dados_novos = {'Gustavo': 20, 'Alana': 30}
serie_dados3 = pd.Series(dados_novos)
serie_dados3

Gustavo    20
Alana      30
dtype: int64

In [140]:
dict_serie_dados

Joao       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [141]:
# Concatenando Series
conct_series = pd.concat([dict_serie_dados, serie_dados3])
conct_series

Joao       10
Alice       5
Gustavo     6
Pedro       9
Gustavo    20
Alana      30
dtype: int64

# Acesso aos dados com iloc
- Acessar elementos pelo índice

In [142]:
dataset = pd.read_csv('census.csv', on_bad_lines='skip')

In [143]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [144]:
type(dataset)

pandas.core.frame.DataFrame

In [145]:
dataset

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [146]:
# Acessando valores de uma coluna especifica
serie_idade = dataset['age']
serie_idade

0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, Length: 32561, dtype: int64

In [147]:
type(serie_idade)

pandas.core.series.Series

In [148]:
# Retornando como Array do NumPy
dataset['age'].values, type(dataset['age'].values)

(array([39, 50, 38, ..., 58, 22, 52]), numpy.ndarray)

In [149]:
serie_idade.head() # Retornando os 5 primeiros registros
# Ou
# serie_idade.head(10) # Retornando os 10 primeiros

0    39
1    50
2    38
3    53
4    28
Name: age, dtype: int64

In [150]:
serie_idade.tail() # Retorna os 5 últimos registros na Serie
# Ou
# serie_idade.tail(10) Assim podemos escolher a quantidade de registros que será retornado.

32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, dtype: int64

## Acessando Dados com o iloc

In [151]:
serie_idade.iloc[0] # Acessando o primeiro registro

np.int64(39)

In [152]:
serie_idade.iloc[24039]

np.int64(26)

In [153]:
serie_idade.iloc[-1] # Retorna o último elemento

np.int64(52)

In [154]:
serie_idade.iloc[0:3] # Buscando elementos de acordo com um intervalo

0    39
1    50
2    38
Name: age, dtype: int64

In [155]:
serie_idade.iloc[[0,2,4]] # Retornando se determinados elementos existem

0    39
2    38
4    28
Name: age, dtype: int64

In [156]:
lista_idade = []
for i in serie_idade.items():
    #print(i)
    #print(i[0], i[1])
    if i[1] > 50:
        lista_idade.append(i[1])

In [157]:
len(lista_idade) # Verificando a quantidade de registro

6460

In [158]:
print(lista_idade)

[53, 52, 54, 59, 56, 54, 53, 57, 53, 53, 79, 67, 52, 59, 53, 57, 76, 56, 53, 56, 55, 61, 70, 64, 52, 71, 68, 66, 51, 53, 58, 51, 58, 60, 54, 64, 90, 54, 53, 60, 66, 75, 65, 59, 56, 58, 59, 58, 59, 64, 61, 60, 57, 65, 55, 77, 62, 76, 63, 58, 66, 55, 53, 67, 56, 59, 65, 62, 56, 57, 54, 52, 52, 63, 80, 51, 60, 54, 52, 60, 67, 52, 63, 59, 72, 62, 52, 58, 53, 57, 74, 67, 57, 58, 72, 69, 54, 52, 51, 58, 65, 57, 59, 52, 57, 55, 60, 60, 51, 52, 52, 65, 58, 52, 60, 71, 58, 70, 58, 66, 54, 60, 65, 55, 56, 55, 55, 58, 54, 59, 53, 51, 55, 54, 61, 59, 60, 61, 68, 64, 56, 64, 57, 62, 53, 73, 72, 55, 63, 51, 62, 55, 61, 59, 71, 51, 55, 63, 54, 63, 51, 53, 53, 67, 81, 64, 51, 51, 54, 51, 51, 55, 67, 78, 60, 63, 51, 56, 58, 66, 54, 51, 51, 56, 76, 66, 90, 64, 61, 53, 52, 61, 54, 58, 62, 68, 69, 60, 58, 53, 63, 59, 56, 61, 51, 51, 54, 65, 88, 51, 58, 51, 59, 65, 51, 51, 59, 61, 61, 54, 63, 53, 55, 75, 52, 55, 65, 62, 54, 51, 52, 57, 53, 69, 73, 51, 67, 52, 65, 57, 58, 63, 58, 51, 61, 55, 52, 57, 51, 71, 57, 59, 61, 62, 58, 61, 52, 51, 53, 52, 61, 54, 65, 59, 54, 54, 51, 55, 53, 52, 53, 57, 59, 58, 61, 56, 51, 60, 56, 76, 70, 61, 69, 58, 53, 57, 53, 64, 60, 58, 66, 59, 59, 52, 62, 59, 69, 56, 62, 75, 51, 52, 72, 51, 65, 55, 57, 57, 67, 58, 54, 60, 61, 51, 52, 67, 57, 54, 52, 65, 55, 71, 59, 55, 62, 52, 51, 64, 53, 53, 51, 54, 56, 73, 51, 55, 64, 57, 60, 53, 51, 65, 71, 51, 59, 66, 63, 52, 59, 73, 52, 57, 51, 52, 51, 51, 52, 56, 58, 70, 53, 63, 61, 60, 63, 68, 55, 68, 62, 68, 65, 52, 57, 90, 56, 57, 77, 66, 68, 64, 51, 55, 53, 60, 54, 75, 51, 66, 72, 57, 57, 63, 61, 53, 53, 53, 60, 66, 63, 51, 51, 59, 51, 51, 56, 52, 61, 52, 58, 66, 57, 61, 61, 54, 56, 52, 58, 75, 66, 57, 61, 59, 51, 60, 64, 54, 63, 74, 65, 55, 60, 64, 53, 57, 51, 59, 60, 54, 51, 63, 51, 58, 64, 63, 52, 56, 90, 53, 64, 56, 58, 58, 62, 65, 63, 56, 53, 51, 62, 67, 61, 74, 57, 55, 54, 63, 56, 53, 70, 57, 54, 51, 55, 66, 68, 61, 55, 60, 61, 61, 54, 60, 64, 69, 69, 55, 74, 75, 55, 52, 54, 76, 57, 60, 52, 61, 57, 59, 70, 51, 54, 52, 65, 63, 54, 59, 51, 55, 58, 54, 53, 56, 54, 56, 67, 52, 57, 51, 77, 67, 60, 56, 74, 52, 54, 55, 66, 52, 52, 55, 70, 51, 62, 64, 55, 61, 78, 55, 61, 64, 56, 56, 52, 72, 51, 54, 62, 58, 57, 55, 53, 80, 56, 51, 55, 59, 61, 61, 54, 64, 55, 61, 53, 53, 54, 63, 57, 58, 69, 54, 56, 56, 53, 71, 65, 90, 56, 64, 67, 53, 81, 55, 63, 56, 52, 75, 53, 60, 68, 75, 53, 61, 55, 64, 62, 72, 55, 64, 55, 51, 57, 51, 60, 61, 71, 61, 54, 53, 57, 59, 69, 72, 74, 51, 60, 65, 61, 52, 54, 55, 64, 60, 51, 55, 64, 56, 59, 58, 53, 53, 58, 54, 59, 51, 71, 51, 62, 59, 82, 74, 59, 59, 53, 57, 58, 52, 56, 52, 64, 73, 52, 58, 59, 74, 62, 76, 53, 61, 58, 56, 68, 59, 63, 59, 53, 79, 57, 57, 51, 61, 51, 51, 61, 53, 58, 66, 52, 52, 61, 54, 53, 63, 53, 59, 56, 55, 63, 59, 55, 69, 55, 52, 62, 51, 55, 59, 52, 63, 81, 57, 56, 67, 51, 56, 51, 57, 57, 58, 68, 53, 63, 54, 74, 61, 59, 53, 72, 61, 73, 65, 52, 52, 63, 71, 60, 76, 63, 61, 53, 55, 57, 62, 51, 75, 53, 51, 70, 70, 58, 53, 54, 64, 56, 68, 57, 55, 51, 52, 74, 80, 63, 63, 51, 66, 52, 53, 53, 65, 68, 54, 51, 51, 54, 57, 52, 62, 55, 60, 51, 51, 62, 54, 68, 61, 51, 54, 63, 51, 63, 51, 53, 54, 62, 57, 53, 69, 56, 53, 61, 51, 72, 57, 52, 53, 75, 53, 63, 52, 62, 83, 59, 67, 55, 64, 52, 77, 52, 54, 63, 64, 59, 72, 57, 57, 51, 51, 58, 66, 90, 59, 52, 59, 59, 57, 51, 52, 90, 65, 54, 65, 56, 55, 52, 66, 63, 66, 52, 54, 54, 63, 67, 66, 67, 76, 51, 59, 55, 64, 54, 53, 51, 54, 75, 61, 51, 68, 52, 72, 59, 64, 64, 59, 66, 54, 58, 56, 65, 64, 63, 51, 68, 51, 56, 54, 53, 63, 53, 67, 64, 53, 52, 54, 52, 52, 60, 51, 54, 52, 53, 56, 58, 64, 53, 52, 56, 68, 57, 52, 56, 73, 51, 64, 53, 59, 55, 60, 52, 61, 60, 57, 56, 63, 57, 53, 51, 67, 55, 58, 52, 57, 54, 65, 55, 53, 77, 58, 59, 66, 58, 59, 53, 64, 62, 61, 51, 56, 55, 59, 60, 79, 60, 69, 55, 55, 51, 62, 65, 60, 70, 76, 54, 65, 63, 66, 67, 58, 59, 51, 69, 59, 56, 51, 52, 56, 53, 81, 57, 68, 60, 60, 75, 57, 58, 51, 54, 55, 60, 63, 65, 60, 51, 51, 56, 55, 52, 58, 55, 63, 76, 56, 57, 59, 52, 63, 55, 55, 53, 55, 52, 52, 57, 62, 68, 61, 53, 52, 53, 65, 62, 54, 90, 57, 52, 59, 55, 60, 57, 52, 58, 57, 51, 54, 73, 58, 67, 65, 66, 51, 61, 63, 76, 76, 53, 63, 51, 54, 61, 51, 51, 52, 57, 52, 58, 52, 63, 51, 57, 59, 90, 54, 80, 77, 53, 57, 59, 52, 58, 53, 74, 61, 54, 60, 90, 55, 63, 59, 61, 63, 57, 90, 60, 71, 74, 67, 59, 63, 53, 51, 56, 52, 56, 55, 53, 60, 54, 51, 61, 56, 62, 55, 53, 56, 60, 55, 69, 62, 54, 57, 51, 51, 58, 57, 64, 60, 54, 58, 59, 55, 57, 78, 66, 60, 59, 55, 57, 53, 54, 56, 51, 57, 62, 56, 56, 53, 72, 54, 51, 76, 60, 60, 55, 53, 69, 71, 59, 63, 51, 51, 56, 60, 56, 61, 60, 56, 57, 54, 62, 52, 58, 52, 61, 51, 76, 53, 53, 65, 54, 60, 78, 58, 67, 73, 66, 66, 64, 51, 51, 59, 62, 58, 64, 63, 60, 55, 73, 57, 57, 52, 71, 52, 53, 56, 51, 59, 64, 53, 62, 58, 56, 79, 51, 52, 51, 67, 65, 57, 51, 52, 55, 61, 78, 55, 52, 61, 65, 56, 56, 57, 58, 55, 52, 56, 55, 55, 51, 59, 58, 54, 57, 54, 57, 56, 60, 58, 56, 58, 63, 51, 64, 54, 59, 57, 53, 58, 55, 51, 70, 61, 56, 79, 60, 58, 71, 60, 84, 55, 55, 54, 52, 52, 66, 90, 67, 55, 56, 53, 51, 63, 55, 51, 52, 70, 53, 59, 70, 77, 51, 58, 54, 57, 66, 70, 75, 51, 61, 59, 56, 57, 61, 58, 51, 64, 55, 54, 74, 58, 54, 80, 55, 51, 60, 51, 55, 62, 59, 70, 52, 67, 53, 54, 54, 53, 57, 51, 51, 54, 66, 61, 51, 63, 63, 55, 75, 61, 53, 55, 58, 61, 64, 51, 77, 66, 62, 66, 56, 90, 72, 57, 54, 58, 52, 51, 58, 63, 51, 60, 54, 55, 57, 56, 51, 51, 61, 58, 52, 63, 61, 75, 81, 54, 54, 61, 63, 53, 63, 71, 57, 54, 51, 59, 67, 64, 52, 73, 59, 55, 55, 56, 68, 60, 52, 58, 67, 63, 51, 54, 52, 73, 52, 57, 56, 59, 53, 54, 60, 65, 67, 62, 55, 56, 60, 63, 60, 69, 51, 60, 69, 54, 56, 63, 64, 55, 63, 57, 58, 61, 56, 73, 64, 52, 61, 58, 51, 56, 59, 55, 56, 58, 56, 56, 55, 53, 57, 52, 58, 54, 69, 52, 52, 68, 54, 64, 56, 67, 52, 65, 64, 63, 53, 63, 53, 52, 53, 58, 54, 51, 53, 54, 53, 63, 59, 66, 64, 60, 67, 58, 53, 60, 52, 60, 56, 59, 60, 60, 59, 55, 55, 62, 51, 56, 53, 54, 68, 54, 54, 70, 83, 59, 53, 66, 74, 51, 51, 53, 62, 54, 71, 56, 64, 54, 64, 61, 51, 63, 51, 60, 60, 61, 65, 56, 55, 62, 62, 65, 60, 53, 57, 64, 58, 51, 53, 58, 57, 69, 56, 70, 58, 58, 69, 84, 53, 58, 51, 56, 54, 68, 56, 69, 62, 53, 53, 58, 52, 52, 55, 54, 53, 62, 59, 58, 61, 51, 70, 55, 68, 57, 53, 59, 81, 51, 52, 59, 73, 62, 52, 51, 54, 58, 58, 67, 55, 51, 66, 60, 53, 51, 51, 64, 62, 52, 55, 61, 57, 54, 55, 67, 54, 51, 59, 52, 53, 57, 59, 52, 51, 59, 57, 60, 53, 63, 79, 60, 58, 59, 68, 56, 73, 66, 51, 65, 57, 65, 62, 76, 52, 62, 62, 56, 55, 56, 57, 73, 51, 58, 69, 69, 54, 64, 53, 57, 51, 54, 53, 58, 61, 56, 59, 72, 51, 61, 64, 62, 53, 56, 61, 85, 60, 69, 65, 51, 56, 82, 67, 78, 67, 66, 52, 59, 72, 63, 58, 75, 52, 66, 54, 61, 79, 64, 70, 51, 77, 62, 69, 57, 64, 59, 51, 53, 62, 62, 59, 57, 70, 53, 60, 57, 65, 60, 61, 58, 59, 58, 65, 80, 70, 52, 67, 55, 62, 64, 52, 56, 53, 51, 54, 53, 52, 55, 55, 57, 56, 57, 57, 61, 60, 58, 90, 69, 58, 69, 53, 54, 66, 68, 56, 57, 53, 61, 64, 52, 63, 65, 57, 55, 73, 76, 54, 51, 56, 53, 60, 65, 57, 57, 59, 90, 61, 55, 90, 63, 60, 53, 53, 58, 51, 58, 62, 56, 56, 51, 57, 77, 55, 74, 51, 58, 52, 53, 54, 73, 67, 56, 59, 58, 68, 66, 71, 54, 52, 68, 51, 57, 66, 77, 70, 59, 75, 53, 58, 72, 51, 54, 60, 58, 58, 55, 60, 53, 72, 52, 58, 60, 59, 53, 59, 52, 54, 59, 54, 64, 51, 52, 51, 52, 63, 52, 69, 59, 51, 64, 51, 69, 62, 58, 64, 66, 55, 53, 60, 54, 60, 62, 54, 62, 54, 58, 64, 55, 58, 55, 59, 55, 84, 62, 52, 62, 52, 63, 70, 61, 61, 58, 58, 65, 52, 52, 52, 60, 69, 56, 65, 73, 62, 53, 53, 58, 63, 55, 58, 55, 55, 53, 60, 53, 52, 62, 51, 57, 62, 64, 62, 69, 57, 52, 64, 70, 58, 60, 51, 56, 52, 55, 51, 62, 52, 52, 51, 62, 69, 78, 61, 64, 51, 57, 78, 61, 67, 58, 51, 55, 52, 66, 59, 67, 52, 63, 51, 64, 67, 60, 56, 55, 59, 53, 63, 61, 56, 51, 61, 63, 63, 55, 58, 52, 53, 68, 59, 76, 65, 64, 68, 53, 51, 69, 73, 67, 63, 67, 51, 61, 73, 67, 55, 64, 54, 51, 53, 68, 56, 70, 74, 61, 61, 52, 71, 56, 62, 58, 57, 51, 61, 51, 52, 56, 51, 80, 57, 51, 77, 51, 51, 58, 52, 59, 54, 65, 55, 68, 60, 56, 59, 51, 55, 90, 52, 54, 51, 54, 55, 52, 59, 74, 52, 56, 52, 55, 55, 63, 51, 67, 54, 59, 51, 69, 59, 64, 70, 54, 62, 61, 73, 65, 64, 56, 60, 52, 56, 67, 51, 54, 59, 59, 51, 60, 63, 63, 51, 64, 65, 51, 58, 63, 63, 51, 56, 56, 53, 52, 74, 56, 54, 56, 55, 67, 60, 54, 66, 51, 90, 78, 77, 70, 51, 66, 57, 51, 60, 57, 69, 51, 53, 52, 54, 62, 57, 65, 52, 59, 71, 57, 71, 57, 64, 58, 53, 54, 68, 77, 70, 57, 55, 61, 55, 56, 76, 64, 63, 54, 53, 55, 58, 76, 67, 61, 58, 52, 54, 65, 68, 51, 57, 53, 59, 51, 71, 74, 64, 56, 53, 54, 59, 58, 53, 63, 72, 51, 68, 56, 52, 56, 52, 51, 58, 54, 60, 65, 52, 66, 53, 54, 52, 60, 61, 55, 55, 68, 72, 58, 62, 58, 53, 52, 69, 57, 55, 79, 67, 55, 55, 52, 51, 73, 52, 57, 52, 65, 59, 73, 64, 62, 51, 54, 65, 60, 62, 66, 70, 74, 51, 58, 66, 84, 53, 54, 78, 57, 70, 58, 59, 62, 51, 73, 52, 67, 55, 63, 66, 65, 60, 60, 75, 58, 65, 52, 59, 53, 73, 58, 53, 51, 63, 62, 56, 58, 59, 52, 61, 59, 56, 67, 54, 52, 62, 53, 69, 56, 54, 73, 69, 54, 76, 73, 74, 90, 69, 52, 79, 63, 63, 65, 62, 61, 63, 57, 64, 56, 55, 71, 56, 51, 53, 54, 52, 59, 59, 52, 52, 51, 67, 58, 68, 71, 57, 51, 69, 59, 64, 56, 51, 67, 51, 55, 67, 62, 73, 61, 90, 76, 65, 58, 54, 69, 61, 57, 56, 51, 78, 61, 55, 53, 54, 62, 59, 68, 59, 58, 67, 54, 52, 52, 51, 57, 60, 63, 53, 56, 58, 57, 71, 54, 57, 55, 54, 58, 60, 52, 59, 51, 58, 55, 76, 51, 51, 53, 61, 90, 51, 55, 65, 67, 56, 52, 53, 65, 54, 70, 53, 55, 63, 61, 55, 61, 56, 66, 65, 52, 55, 54, 67, 56, 54, 60, 55, 72, 53, 69, 55, 64, 53, 61, 64, 53, 55, 52, 57, 60, 65, 52, 57, 61, 53, 52, 57, 58, 57, 57, 54, 55, 76, 75, 51, 60, 73, 57, 53, 55, 72, 60, 55, 68, 52, 68, 52, 53, 57, 59, 59, 62, 63, 60, 52, 60, 64, 69, 61, 70, 68, 52, 71, 55, 57, 55, 55, 59, 54, 90, 56, 60, 57, 56, 59, 82, 60, 60, 63, 65, 62, 60, 51, 53, 52, 64, 53, 56, 56, 62, 65, 65, 56, 51, 57, 74, 56, 56, 62, 52, 63, 51, 62, 61, 70, 55, 53, 77, 51, 61, 63, 65, 51, 56, 69, 52, 63, 58, 67, 62, 58, 58, 60, 55, 64, 55, 65, 68, 57, 51, 52, 64, 51, 51, 52, 58, 53, 54, 81, 69, 52, 57, 57, 60, 51, 60, 59, 56, 56, 56, 61, 51, 54, 59, 65, 56, 57, 61, 67, 51, 60, 69, 65, 52, 52, 67, 64, 51, 52, 90, 60, 53, 76, 58, 52, 62, 64, 51, 57, 54, 52, 84, 79, 56, 54, 60, 58, 53, 71, 58, 63, 61, 62, 57, 56, 53, 51, 77, 64, 67, 60, 51, 52, 66, 51, 71, 63, 51, 65, 53, 53, 54, 71, 62, 66, 63, 55, 63, 54, 78, 77, 54, 62, 69, 53, 68, 57, 58, 68, 65, 55, 66, 53, 64, 65, 53, 61, 59, 81, 55, 60, 54, 51, 64, 61, 56, 56, 71, 51, 54, 52, 63, 54, 57, 54, 57, 57, 61, 53, 75, 60, 56, 66, 55, 65, 61, 51, 75, 55, 64, 65, 58, 63, 59, 51, 51, 57, 62, 64, 52, 54, 59, 74, 54, 54, 57, 57, 53, 64, 55, 55, 58, 57, 54, 71, 68, 78, 62, 55, 51, 62, 58, 64, 55, 70, 57, 52, 51, 63, 82, 59, 57, 60, 56, 51, 63, 58, 51, 72, 61, 65, 64, 61, 73, 66, 53, 57, 59, 52, 59, 63, 51, 56, 52, 59, 53, 54, 58, 53, 65, 54, 58, 72, 63, 58, 56, 55, 57, 57, 53, 70, 72, 64, 55, 55, 52, 73, 66, 69, 55, 70, 54, 60, 81, 51, 66, 65, 54, 77, 66, 52, 61, 52, 76, 54, 60, 76, 57, 52, 57, 51, 61, 71, 61, 57, 56, 60, 54, 51, 64, 54, 68, 59, 53, 59, 74, 80, 51, 58, 57, 57, 53, 52, 57, 51, 69, 63, 56, 90, 55, 66, 66, 71, 52, 52, 69, 54, 66, 61, 55, 56, 58, 62, 54, 53, 56, 57, 62, 72, 53, 54, 59, 69, 68, 65, 52, 54, 55, 51, 65, 58, 53, 56, 59, 75, 64, 67, 53, 73, 64, 54, 56, 54, 75, 62, 58, 52, 56, 52, 68, 64, 74, 51, 67, 67, 51, 53, 61, 67, 61, 60, 64, 52, 57, 51, 59, 65, 57, 51, 65, 52, 56, 59, 63, 53, 59, 60, 61, 66, 60, 68, 55, 66, 58, 56, 51, 53, 80, 61, 55, 71, 67, 56, 57, 62, 65, 55, 54, 52, 57, 58, 58, 72, 51, 51, 54, 62, 84, 67, 63, 55, 60, 65, 61, 51, 56, 82, 52, 53, 52, 57, 58, 59, 56, 58, 55, 52, 55, 55, 56, 60, 65, 73, 54, 55, 53, 51, 62, 58, 72, 72, 60, 70, 60, 51, 78, 72, 58, 56, 79, 55, 59, 67, 61, 65, 53, 53, 58, 51, 51, 56, 63, 61, 52, 59, 55, 66, 51, 52, 52, 70, 62, 52, 58, 64, 55, 52, 51, 62, 51, 52, 65, 60, 62, 53, 52, 63, 63, 62, 51, 76, 51, 53, 60, 54, 57, 51, 53, 54, 53, 57, 57, 74, 61, 56, 68, 62, 62, 65, 53, 54, 59, 73, 55, 53, 53, 74, 53, 60, 59, 73, 58, 62, 58, 51, 52, 54, 59, 55, 70, 54, 54, 54, 67, 57, 60, 53, 53, 57, 62, 52, 57, 56, 90, 54, 59, 55, 67, 51, 55, 55, 59, 51, 51, 62, 51, 57, 63, 59, 67, 64, 56, 57, 56, 66, 71, 61, 51, 51, 52, 67, 58, 67, 61, 55, 51, 51, 62, 54, 54, 68, 59, 53, 53, 52, 53, 53, 61, 74, 75, 61, 60, 51, 53, 68, 63, 58, 63, 59, 54, 66, 59, 62, 60, 58, 59, 72, 68, 56, 52, 52, 84, 66, 62, 60, 60, 51, 57, 68, 56, 56, 62, 55, 51, 52, 53, 56, 58, 59, 53, 63, 52, 53, 67, 58, 52, 55, 64, 61, 53, 60, 51, 59, 66, 53, 68, 62, 57, 58, 59, 56, 60, 73, 90, 62, 62, 61, 56, 58, 54, 72, 54, 58, 65, 52, 65, 53, 58, 60, 54, 63, 51, 59, 67, 65, 55, 63, 57, 74, 54, 63, 58, 68, 64, 54, 57, 55, 69, 57, 58, 58, 59, 53, 54, 51, 59, 55, 65, 60, 57, 57, 51, 53, 54, 58, 59, 58, 69, 74, 58, 54, 60, 62, 63, 51, 71, 69, 57, 58, 56, 55, 62, 57, 51, 58, 56, 60, 56, 51, 58, 57, 68, 70, 51, 62, 51, 57, 54, 52, 52, 59, 56, 58, 52, 55, 61, 64, 56, 56, 61, 63, 55, 51, 56, 83, 52, 52, 58, 59, 61, 51, 53, 63, 53, 68, 57, 66, 54, 59, 64, 61, 53, 67, 54, 57, 57, 51, 55, 55, 59, 56, 57, 53, 59, 52, 62, 55, 58, 67, 52, 59, 54, 57, 51, 51, 72, 58, 63, 51, 75, 52, 69, 52, 51, 75, 55, 61, 79, 51, 62, 63, 64, 59, 70, 66, 61, 59, 68, 73, 51, 53, 53, 53, 59, 62, 60, 52, 54, 51, 65, 78, 59, 55, 61, 53, 59, 60, 55, 51, 51, 52, 64, 81, 55, 52, 54, 64, 51, 63, 51, 69, 56, 66, 55, 73, 53, 71, 69, 51, 53, 53, 53, 63, 54, 58, 80, 52, 62, 58, 59, 58, 62, 55, 62, 51, 66, 54, 54, 71, 51, 75, 57, 64, 53, 52, 51, 77, 72, 78, 51, 60, 56, 57, 61, 56, 61, 60, 56, 58, 55, 51, 54, 53, 61, 65, 67, 51, 54, 51, 59, 66, 66, 51, 52, 63, 57, 54, 52, 57, 51, 58, 61, 57, 58, 59, 53, 54, 60, 58, 56, 58, 57, 59, 52, 54, 52, 65, 63, 57, 64, 73, 57, 55, 59, 59, 58, 66, 75, 60, 52, 55, 76, 57, 53, 55, 65, 70, 57, 63, 51, 59, 58, 51, 62, 59, 57, 51, 69, 51, 64, 61, 51, 54, 63, 70, 62, 61, 52, 61, 69, 70, 52, 59, 53, 55, 78, 68, 51, 53, 53, 64, 57, 51, 52, 64, 58, 71, 52, 59, 76, 57, 56, 55, 52, 55, 55, 62, 79, 61, 60, 51, 52, 62, 51, 63, 63, 61, 57, 65, 57, 59, 59, 68, 63, 56, 62, 58, 69, 54, 65, 56, 51, 62, 60, 51, 66, 52, 67, 54, 69, 67, 51, 60, 58, 55, 54, 57, 58, 54, 60, 66, 62, 57, 57, 57, 64, 55, 68, 58, 55, 54, 52, 57, 67, 58, 66, 58, 62, 53, 71, 52, 56, 58, 57, 58, 68, 53, 53, 60, 59, 53, 55, 56, 54, 51, 66, 71, 60, 54, 63, 64, 53, 80, 53, 58, 52, 52, 54, 55, 71, 72, 65, 68, 72, 56, 58, 55, 64, 51, 79, 58, 63, 65, 51, 52, 53, 56, 71, 51, 52, 57, 52, 59, 67, 72, 58, 56, 51, 53, 54, 62, 64, 60, 67, 53, 55, 58, 74, 61, 57, 80, 90, 55, 72, 65, 54, 55, 60, 58, 57, 51, 62, 68, 53, 62, 72, 74, 70, 52, 66, 51, 54, 69, 90, 65, 58, 57, 67, 54, 70, 61, 51, 51, 66, 57, 74, 65, 64, 54, 56, 66, 60, 54, 57, 62, 55, 62, 70, 71, 52, 53, 59, 65, 53, 63, 67, 52, 54, 68, 80, 63, 64, 73, 53, 58, 53, 54, 56, 60, 59, 59, 60, 52, 63, 63, 58, 70, 62, 58, 59, 66, 52, 56, 64, 70, 59, 51, 73, 51, 57, 55, 60, 73, 73, 54, 68, 60, 90, 58, 65, 69, 58, 58, 53, 54, 52, 54, 51, 55, 59, 68, 56, 58, 57, 90, 66, 73, 53, 53, 53, 53, 52, 54, 53, 59, 53, 58, 68, 55, 52, 54, 56, 59, 66, 63, 58, 65, 51, 58, 52, 62, 53, 61, 68, 55, 58, 56, 51, 56, 65, 52, 61, 63, 52, 60, 81, 56, 57, 53, 58, 53, 56, 55, 51, 62, 62, 57, 60, 51, 61, 52, 76, 58, 62, 60, 51, 71, 73, 66, 60, 59, 58, 58, 69, 59, 53, 53, 53, 58, 60, 67, 52, 83, 51, 51, 82, 53, 66, 64, 62, 52, 52, 90, 69, 57, 73, 57, 69, 56, 53, 54, 53, 56, 60, 53, 67, 64, 53, 59, 61, 51, 70, 65, 64, 68, 60, 55, 52, 72, 62, 59, 67, 60, 63, 55, 53, 58, 55, 58, 62, 58, 61, 59, 67, 58, 52, 53, 52, 55, 64, 55, 63, 56, 59, 53, 90, 63, 76, 81, 56, 58, 55, 80, 56, 63, 54, 54, 71, 51, 52, 55, 51, 54, 60, 55, 53, 64, 61, 51, 54, 55, 57, 51, 63, 59, 64, 53, 57, 51, 53, 68, 51, 52, 52, 53, 69, 56, 56, 80, 52, 54, 66, 70, 58, 60, 61, 52, 52, 58, 57, 90, 66, 52, 63, 58, 59, 64, 63, 51, 55, 55, 60, 53, 58, 61, 52, 64, 54, 79, 55, 60, 53, 58, 55, 60, 52, 77, 53, 58, 57, 77, 51, 53, 60, 53, 70, 55, 56, 62, 58, 55, 54, 55, 53, 66, 59, 61, 67, 59, 56, 63, 59, 56, 55, 72, 54, 63, 72, 55, 71, 57, 56, 64, 61, 52, 60, 65, 61, 68, 65, 58, 54, 57, 56, 62, 65, 65, 55, 56, 59, 56, 63, 51, 65, 54, 70, 52, 64, 52, 62, 68, 62, 56, 55, 52, 64, 52, 53, 52, 60, 64, 63, 54, 63, 54, 54, 60, 51, 57, 53, 52, 52, 54, 51, 60, 65, 55, 80, 59, 52, 56, 69, 51, 66, 52, 65, 70, 58, 65, 65, 55, 66, 69, 53, 60, 76, 54, 63, 51, 56, 61, 58, 66, 55, 60, 60, 70, 58, 54, 65, 82, 68, 54, 59, 70, 57, 63, 60, 64, 71, 55, 85, 57, 58, 57, 64, 55, 80, 79, 58, 51, 52, 68, 65, 52, 62, 51, 57, 59, 55, 57, 55, 52, 62, 73, 68, 54, 63, 67, 67, 54, 54, 72, 90, 71, 56, 57, 55, 66, 58, 62, 77, 51, 58, 55, 68, 60, 57, 59, 60, 55, 52, 62, 56, 55, 61, 55, 55, 71, 62, 51, 56, 51, 62, 76, 54, 55, 56, 55, 54, 81, 57, 65, 53, 58, 51, 52, 53, 76, 56, 51, 58, 55, 60, 61, 63, 61, 53, 79, 54, 51, 59, 59, 55, 77, 60, 52, 52, 58, 59, 52, 57, 80, 52, 63, 52, 52, 60, 54, 61, 59, 51, 61, 53, 51, 54, 60, 57, 63, 55, 64, 64, 56, 59, 70, 76, 60, 54, 54, 54, 61, 53, 68, 54, 52, 58, 67, 69, 61, 76, 53, 59, 63, 57, 58, 59, 58, 53, 74, 64, 63, 52, 55, 71, 51, 53, 58, 51, 60, 58, 62, 59, 64, 51, 68, 65, 52, 61, 61, 53, 51, 69, 55, 60, 62, 65, 57, 53, 62, 61, 51, 59, 65, 79, 54, 77, 62, 61, 62, 57, 60, 62, 66, 54, 62, 60, 74, 63, 59, 51, 55, 54, 52, 59, 55, 54, 53, 53, 58, 55, 74, 56, 57, 59, 58, 75, 81, 59, 78, 61, 52, 55, 51, 52, 55, 65, 59, 52, 51, 53, 62, 55, 60, 61, 71, 51, 55, 52, 52, 69, 57, 69, 61, 52, 51, 55, 65, 56, 57, 56, 68, 68, 59, 66, 67, 72, 60, 67, 77, 62, 52, 61, 55, 66, 63, 55, 82, 60, 53, 51, 57, 56, 55, 88, 60, 56, 67, 53, 51, 63, 52, 51, 65, 58, 57, 65, 71, 67, 56, 57, 54, 63, 67, 65, 52, 55, 62, 70, 57, 70, 51, 59, 57, 56, 72, 76, 53, 69, 55, 52, 58, 52, 58, 52, 58, 67, 62, 54, 56, 59, 53, 52, 66, 55, 54, 59, 55, 67, 56, 57, 57, 59, 56, 53, 59, 59, 55, 53, 56, 55, 54, 52, 53, 90, 53, 56, 62, 67, 59, 63, 56, 69, 56, 61, 59, 59, 54, 53, 54, 56, 53, 52, 61, 54, 56, 69, 51, 64, 68, 51, 52, 51, 52, 52, 51, 58, 53, 60, 68, 51, 55, 51, 71, 59, 51, 67, 68, 53, 57, 82, 65, 63, 59, 62, 59, 51, 54, 56, 52, 60, 62, 65, 64, 55, 63, 53, 53, 59, 53, 55, 53, 61, 58, 51, 51, 60, 51, 56, 60, 64, 51, 53, 57, 51, 59, 51, 54, 53, 53, 51, 54, 76, 53, 53, 52, 53, 61, 53, 66, 65, 71, 56, 60, 65, 53, 53, 53, 55, 57, 53, 61, 61, 58, 56, 59, 65, 57, 60, 61, 57, 54, 58, 88, 84, 58, 57, 52, 59, 60, 69, 60, 64, 51, 51, 74, 57, 54, 71, 62, 56, 51, 53, 58, 52, 56, 56, 56, 62, 52, 59, 59, 64, 53, 70, 59, 63, 53, 65, 64, 68, 56, 68, 53, 56, 53, 75, 51, 68, 57, 54, 56, 64, 60, 65, 72, 59, 59, 59, 52, 51, 55, 61, 52, 51, 61, 72, 54, 58, 62, 67, 63, 60, 51, 66, 52, 71, 59, 55, 63, 59, 58, 66, 57, 57, 56, 56, 56, 71, 70, 76, 64, 53, 52, 77, 53, 57, 62, 66, 63, 52, 55, 64, 51, 56, 55, 70, 83, 69, 54, 71, 56, 55, 58, 51, 59, 56, 60, 53, 62, 58, 76, 60, 72, 59, 59, 69, 54, 65, 70, 53, 55, 53, 71, 52, 56, 64, 54, 61, 62, 51, 54, 54, 51, 52, 58, 53, 55, 54, 56, 72, 53, 70, 56, 55, 55, 57, 70, 56, 64, 56, 72, 69, 56, 58, 58, 63, 56, 58, 55, 61, 57, 62, 60, 67, 55, 65, 72, 75, 51, 51, 67, 59, 68, 60, 51, 52, 51, 56, 71, 69, 58, 62, 51, 64, 54, 66, 63, 65, 51, 67, 77, 57, 54, 51, 51, 68, 58, 61, 57, 79, 73, 59, 62, 71, 60, 65, 77, 59, 59, 56, 58, 70, 60, 59, 62, 55, 55, 63, 51, 58, 65, 52, 53, 86, 60, 59, 64, 90, 51, 62, 62, 63, 54, 61, 67, 60, 56, 54, 52, 52, 58, 61, 59, 59, 66, 55, 56, 55, 52, 62, 70, 51, 58, 77, 54, 59, 56, 59, 52, 69, 60, 51, 75, 58, 58, 51, 67, 90, 62, 70, 65, 57, 66, 53, 61, 58, 56, 61, 66, 67, 59, 82, 57, 55, 72, 68, 54, 56, 66, 51, 65, 53, 56, 51, 53, 52, 61, 55, 62, 55, 57, 67, 51, 51, 62, 54, 55, 51, 60, 62, 83, 60, 76, 52, 73, 60, 54, 58, 55, 63, 62, 52, 58, 52, 54, 60, 54, 60, 52, 51, 51, 61, 51, 69, 63, 55, 52, 56, 60, 70, 57, 68, 59, 53, 63, 60, 55, 51, 53, 81, 56, 52, 52, 62, 57, 52, 57, 64, 56, 52, 54, 53, 64, 62, 57, 56, 53, 72, 52, 60, 68, 53, 60, 67, 57, 53, 51, 51, 54, 59, 54, 54, 67, 51, 58, 51, 59, 54, 58, 56, 74, 62, 51, 73, 52, 57, 58, 72, 53, 54, 61, 57, 63, 69, 69, 58, 54, 55, 63, 62, 51, 61, 61, 55, 64, 58, 56, 53, 68, 69, 62, 62, 65, 52, 53, 55, 67, 55, 53, 58, 53, 57, 57, 54, 52, 53, 53, 66, 60, 63, 65, 61, 55, 59, 70, 53, 74, 57, 56, 51, 51, 57, 61, 59, 52, 55, 75, 79, 59, 63, 58, 51, 51, 52, 52, 74, 61, 65, 53, 54, 58, 52, 53, 58,

In [159]:
serie_idade.iloc[lista_idade]

53    50
52    47
54    47
59    30
56    46
      ..
72    29
65    36
53    50
58    41
52    47
Name: age, Length: 6460, dtype: int64

# Acesso aos dados com loc
- Acessar elementos por "String"

In [160]:
# Biblioteca que contem dados testes
!pip install Faker

Collecting Faker
  Downloading faker-40.37.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.37.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 21.6 MB/s eta 0:00:00
Installing collected packages: Faker
Successfully installed Faker-40.37.0

In [161]:
from faker import Faker # Importando a biblioteca de amostragem
fake = Faker() # Fazendo a implementação

In [162]:
fake.name() # Chamando a função

'Dustin Stevenson'

In [163]:
indices_nome = [] # Criando uma lista vazia
for _ in range(32561): # Gerando uma lista de nome de acordo com a quantidade registros  no CSV
    indices_nome.append(fake.name()) # A função Append inlui os nomes gerandos na lista

In [164]:
type(indices_nome), len(indices_nome) # Verificando o tipo e a quantidade de dados, ou tamanho

(list, 32561)

In [165]:
indices_nome[0:10]

['John Bird',
 'Allison Olsen',
 'Taylor Smith',
 'Shane Thomas',
 'April Reynolds',
 'Terri Rivera',
 'Kayla Hawkins',
 'Mackenzie Lawrence',
 'Christine Campbell',
 'Jennifer Wyatt']

In [166]:
serie_idade.size

32561

In [167]:
serie_idade_nome = pd.Series(np.array(dataset['age']), index = indices_nome) # Mesclando os nomes gerados com a lista do CSV, nesse caso puxando apenas a idade.
serie_idade_nome

John Bird         39
Allison Olsen     50
Taylor Smith      38
Shane Thomas      53
April Reynolds    28
                  ..
April Hall        27
Caleb Lloyd       40
Angela Morse      58
Richard Murphy    22
Anna Patterson    52
Length: 32561, dtype: int64

In [168]:
#serie_idade_nome.loc["Brandy Coleman":"Dean Daniel"] # Fazendo uma busca com intervalo entre dois registro

In [169]:
serie_idade_nome2 = serie_idade_nome.drop_duplicates() # Apagando registros duplicados na lista gerada
serie_idade_nome2.size # Verificando o tamanho da lista
serie_idade_nome2

John Bird               39
Allison Olsen           50
Taylor Smith            38
Shane Thomas            53
April Reynolds          28
                        ..
Miss Erin Parker PhD    83
Kimberly Taylor         84
Misty Ayers             85
Thomas Smith            86
Patrick Murphy          87
Length: 73, dtype: int64

In [170]:
serie_idade_nome2.index # Verificando o indices da lista

Index(['John Bird', 'Allison Olsen', 'Taylor Smith', 'Shane Thomas',
       'April Reynolds', 'Terri Rivera', 'Kayla Hawkins', 'Mackenzie Lawrence',
       'Christine Campbell', 'Jennifer Wyatt', 'Allison Townsend',
       'Anthony Gomez', 'Laura Carrillo', 'John Thompson', 'Ruth Davis',
       'Stephanie Reed', 'Sarah Atkinson', 'Patricia Brown',
       'Patrick Williams', 'Jessica Moran', 'Richard Atkins', 'Heather Martin',
       'Adam Quinn', 'Katherine Mcdonald', 'Justin Russell', 'Melissa Foster',
       'Jordan Lucero', 'Timothy Malone', 'Anthony Sellers', 'Courtney Garcia',
       'Christopher Anderson', 'Jennifer Montes', 'Barbara Smith',
       'Katie Hammond', 'Tina Nelson', 'James Brooks', 'Jason Morales',
       'Christian Scott', 'Steven Diaz', 'Madeline Harris', 'Henry Combs',
       'Carol Wilkerson', 'Luke Silva', 'Edwin Carter', 'Michael Scott',
       'Casey Conway', 'Megan Romero', 'William Rivers', 'Theresa Duran',
       'Vanessa Wheeler', 'Diana Vasquez', 'Jenny Reyes', 'Kim Orozco',
       'Dominique Smith', 'Johnathan Palmer', 'Casey Shannon',
       'Nicholas Gonzalez', 'Ronald Maynard', 'Nicole Lopez', 'Bryan Romero',
       'Heather Howell', 'Christopher Nelson', 'Michael Perry', 'Ross White',
       'Bryan Rojas', 'Jason Davis', 'Devin Valentine', 'Elijah Wilson',
       'Miss Erin Parker PhD', 'Kimberly Taylor', 'Misty Ayers',
       'Thomas Smith', 'Patrick Murphy'],
      dtype='object')

In [171]:
#serie_idade_nome2.loc["Brandy Coleman":"Thomas Jackson"]

In [172]:
#serie_idade_nome2.loc[["Brandy Coleman", "Matthew Osborn"]] #  Buscando nomes especificos na lista

In [173]:
serie_idade_nome3 = serie_idade_nome2.copy() # Fazendo uma cópia da lista
serie_idade_nome3

John Bird               39
Allison Olsen           50
Taylor Smith            38
Shane Thomas            53
April Reynolds          28
                        ..
Miss Erin Parker PhD    83
Kimberly Taylor         84
Misty Ayers             85
Thomas Smith            86
Patrick Murphy          87
Length: 73, dtype: int64

In [174]:
#serie_idade_nome3.reset_index(drop = True) <-- Aqui é preciso atribuir a uma variavel para que faça efeito
serie_idade_nome3.reset_index(drop = True, inplace = True) # <- Aqui rescrevemos o valor da atual variavel

In [175]:
serie_idade_nome3

0     39
1     50
2     38
3     53
4     28
      ..
68    83
69    84
70    85
71    86
72    87
Length: 73, dtype: int64

In [176]:
serie_idade_nome3.index

RangeIndex(start=0, stop=73, step=1)

# Ordenação

In [177]:
serie_idade_nome

John Bird         39
Allison Olsen     50
Taylor Smith      38
Shane Thomas      53
April Reynolds    28
                  ..
April Hall        27
Caleb Lloyd       40
Angela Morse      58
Richard Murphy    22
Anna Patterson    52
Length: 32561, dtype: int64

In [178]:
serie_idade_nome.sort_values() # Fazendo a ordenação dos valores, nesse caso não pega nos indices, apenas nos valores

Angela Contreras     17
Rachel Jackson MD    17
Cynthia Smith        17
Stephanie Mcneil     17
Bonnie Craig         17
                     ..
Cameron Morris       90
Cameron Rodriguez    90
Tammy Bennett        90
Allen Moore          90
Monique Cook         90
Length: 32561, dtype: int64

In [179]:
serie_idade_nome.sort_values(ascending =  False) # Fazendo uma ordenação descendente dos valores, não dos indices

Jason Mills          90
Steven Carroll       90
Christina Ellis      90
Janet Winters        90
Darlene Wilson       90
                     ..
Jasmine Gross        17
Charles Austin       17
Kimberly Mckinney    17
Steven Rhodes        17
Stephanie Summers    17
Length: 32561, dtype: int64

In [180]:
serie_idade_nome.sort_index(ascending = False) # Fazendo ordenação dos indices, nesse caso em ordem descendente

Zoe Short           68
Zoe Rose            42
Zoe Nunez           28
Zoe Jordan          50
Zoe Johnson         27
                    ..
Aaron Beasley       46
Aaron Barnes        21
Aaron Banks         49
Aaron Arroyo DDS    68
Aaron Anderson      60
Length: 32561, dtype: int64

In [181]:
serie_idade_nome.sort_index(ascending = True) # Fazendo ordenação dos indices, nesse caso em ordem ascendente

Aaron Anderson      60
Aaron Arroyo DDS    68
Aaron Banks         49
Aaron Barnes        21
Aaron Beasley       46
                    ..
Zoe Johnson         39
Zoe Jordan          50
Zoe Nunez           28
Zoe Rose            42
Zoe Short           68
Length: 32561, dtype: int64

In [182]:
sr = serie_idade_nome.sort_values(ascending = False).iloc[0:10] # Limitando a quantidade de registros, nesse caso ordenando os valores em ordem descendente e buscando do 0 até 10 registro.
sr

Jason Mills        90
Steven Carroll     90
Christina Ellis    90
Janet Winters      90
Darlene Wilson     90
Kelli Gallegos     90
Terrance Ritter    90
Timothy Diaz       90
Grant Parker       90
Cameron Morris     90
dtype: int64

# Contagem

In [183]:
serie_idade_nome.size  # Verificando o tamanho da Serie

32561

In [184]:
serie_idade_nome

John Bird         39
Allison Olsen     50
Taylor Smith      38
Shane Thomas      53
April Reynolds    28
                  ..
April Hall        27
Caleb Lloyd       40
Angela Morse      58
Richard Murphy    22
Anna Patterson    52
Length: 32561, dtype: int64

In [185]:
serie_idade_nome.value_counts() # Fazendo a contagem de registros por valor

36    898
31    888
34    886
23    877
35    876
     ...
83      6
88      3
85      3
86      1
87      1
Name: count, Length: 73, dtype: int64

In [186]:
serie_idade_nome.value_counts(normalize = True) # Adicionando uma função que trasforma a contagem em procentagem

36    0.027579
31    0.027272
34    0.027210
23    0.026934
35    0.026903
        ...
83    0.000184
88    0.000092
85    0.000092
86    0.000031
87    0.000031
Name: proportion, Length: 73, dtype: float64

In [187]:
serie_idade_nome.value_counts(bins = 10) # Fazendo uma divisão, nesse caso a cada 10 valores. 10-20, 30 - 40 e por ai vai

(38.9, 46.2]      6163
(31.6, 38.9]      6048
(24.3, 31.6]      5890
(16.926, 24.3]    5570
(46.2, 53.5]      3967
(53.5, 60.8]      2591
(60.8, 68.1]      1595
(68.1, 75.4]       496
(75.4, 82.7]       174
(82.7, 90.0]        67
Name: count, dtype: int64

# Filtros

In [188]:
fake.country() # Gerando nome de paises aleatoriamente

'Bosnia and Herzegovina'

In [189]:
indices_pais = [] # Criando uma lista vazia
for _ in range(32561):
    indices_pais.append(fake.country()) # Gerando nome de paises para preencher uma lista com valor

In [190]:
indices_pais[0:10] # FIltrando os 10 primeiros registro de uma Serie

['Cook Islands',
 'Seychelles',
 'Cook Islands',
 'Saint Martin',
 'Lesotho',
 'Guam',
 'Costa Rica',
 'Sweden',
 'Colombia',
 'Spain']

In [191]:
serie_pais = pd.Series(
    np.array(dataset['age']), # Pegando apenas a idade e tranformando em um array
    index = indices_pais # Mesclando com indice personalizado
)
serie_pais

Cook Islands                                    39
Seychelles                                      50
Cook Islands                                    38
Saint Martin                                    53
Lesotho                                         28
                                                ..
Palestinian Territory                           27
Western Sahara                                  40
South Georgia and the South Sandwich Islands    58
Libyan Arab Jamahiriya                          22
Serbia                                          52
Length: 32561, dtype: int64

In [192]:
sp = serie_pais.sort_index(ascending = True)
sp.loc[sp > 50]

Afghanistan    51
Afghanistan    76
Afghanistan    57
Afghanistan    59
Afghanistan    59
               ..
Zimbabwe       58
Zimbabwe       61
Zimbabwe       52
Zimbabwe       52
Zimbabwe       60
Length: 6460, dtype: int64

In [193]:
serie_pais.loc[serie_pais > 50] # Filtrando paises que atende a condição maior que 50

Saint Martin                                    53
Sweden                                          52
Sierra Leone                                    54
Syrian Arab Republic                            59
Cocos (Keeling) Islands                         56
                                                ..
Equatorial Guinea                               72
Panama                                          65
Cape Verde                                      53
South Georgia and the South Sandwich Islands    58
Serbia                                          52
Length: 6460, dtype: int64

In [194]:
serie_pais.loc[(serie_pais > 50) & (serie_pais.index == "Brazil")] # Filtrando duas condições com um operador AND

Brazil    64
Brazil    54
Brazil    64
Brazil    51
Brazil    52
Brazil    57
Brazil    63
Brazil    52
Brazil    64
Brazil    64
Brazil    74
Brazil    51
Brazil    52
Brazil    61
Brazil    56
Brazil    81
Brazil    57
Brazil    64
Brazil    54
Brazil    54
Brazil    65
Brazil    51
Brazil    60
Brazil    55
Brazil    54
dtype: int64

In [195]:
serie_pais.index.isin(["India", "Brazil"]) # Esses valores existem na lista?

array([False, False, False, ..., False, False, False])

In [196]:
~serie_pais.index.isin(["India", "Brazil"]) # Esse valor não existem nessa lista?s

array([ True,  True,  True, ...,  True,  True,  True])

# Operações Matemáticas

In [197]:
serie_pais

Cook Islands                                    39
Seychelles                                      50
Cook Islands                                    38
Saint Martin                                    53
Lesotho                                         28
                                                ..
Palestinian Territory                           27
Western Sahara                                  40
South Georgia and the South Sandwich Islands    58
Libyan Arab Jamahiriya                          22
Serbia                                          52
Length: 32561, dtype: int64

In [198]:
serie_pais + 2 # Tradicional do Python

Cook Islands                                    41
Seychelles                                      52
Cook Islands                                    40
Saint Martin                                    55
Lesotho                                         30
                                                ..
Palestinian Territory                           29
Western Sahara                                  42
South Georgia and the South Sandwich Islands    60
Libyan Arab Jamahiriya                          24
Serbia                                          54
Length: 32561, dtype: int64

In [199]:
serie_pais.add(2) # Comando do Pandas

Cook Islands                                    41
Seychelles                                      52
Cook Islands                                    40
Saint Martin                                    55
Lesotho                                         30
                                                ..
Palestinian Territory                           29
Western Sahara                                  42
South Georgia and the South Sandwich Islands    60
Libyan Arab Jamahiriya                          24
Serbia                                          54
Length: 32561, dtype: int64

In [200]:
serie_pais.sub(2)

Cook Islands                                    37
Seychelles                                      48
Cook Islands                                    36
Saint Martin                                    51
Lesotho                                         26
                                                ..
Palestinian Territory                           25
Western Sahara                                  38
South Georgia and the South Sandwich Islands    56
Libyan Arab Jamahiriya                          20
Serbia                                          50
Length: 32561, dtype: int64

In [201]:
serie_pais.mul(2)

Cook Islands                                     78
Seychelles                                      100
Cook Islands                                     76
Saint Martin                                    106
Lesotho                                          56
                                               ...
Palestinian Territory                            54
Western Sahara                                   80
South Georgia and the South Sandwich Islands    116
Libyan Arab Jamahiriya                           44
Serbia                                          104
Length: 32561, dtype: int64

In [202]:
serie_pais.div(2)

Cook Islands                                    19.5
Seychelles                                      25.0
Cook Islands                                    19.0
Saint Martin                                    26.5
Lesotho                                         14.0
                                                ...
Palestinian Territory                           13.5
Western Sahara                                  20.0
South Georgia and the South Sandwich Islands    29.0
Libyan Arab Jamahiriya                          11.0
Serbia                                          26.0
Length: 32561, dtype: float64

In [203]:
s1 = pd.Series([20,30,40])
s2 = pd.Series([1,2,3])
s1,s2

(0    20
 1    30
 2    40
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [204]:
s1.add(s2)

0    21
1    32
2    43
dtype: int64

In [205]:
s1.sub(s2)

0    19
1    28
2    37
dtype: int64

In [206]:
s1.mul(s2)

0     20
1     60
2    120
dtype: int64

# Operações com String

In [207]:
serie_pais

Cook Islands                                    39
Seychelles                                      50
Cook Islands                                    38
Saint Martin                                    53
Lesotho                                         28
                                                ..
Palestinian Territory                           27
Western Sahara                                  40
South Georgia and the South Sandwich Islands    58
Libyan Arab Jamahiriya                          22
Serbia                                          52
Length: 32561, dtype: int64

In [208]:
spi = serie_pais.index.to_series()
spi.reset_index(drop = True, inplace = True)
spi

0                                        Cook Islands
1                                          Seychelles
2                                        Cook Islands
3                                        Saint Martin
4                                             Lesotho
                             ...
32556                           Palestinian Territory
32557                                  Western Sahara
32558    South Georgia and the South Sandwich Islands
32559                          Libyan Arab Jamahiriya
32560                                          Serbia
Length: 32561, dtype: object

In [209]:
spi.str.contains("tse")

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557    False
32558    False
32559    False
32560    False
Length: 32561, dtype: bool

In [210]:
spi.str.upper()

0                                        COOK ISLANDS
1                                          SEYCHELLES
2                                        COOK ISLANDS
3                                        SAINT MARTIN
4                                             LESOTHO
                             ...
32556                           PALESTINIAN TERRITORY
32557                                  WESTERN SAHARA
32558    SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
32559                          LIBYAN ARAB JAMAHIRIYA
32560                                          SERBIA
Length: 32561, dtype: object

In [211]:
spi.str.lower()

0                                        cook islands
1                                          seychelles
2                                        cook islands
3                                        saint martin
4                                             lesotho
                             ...
32556                           palestinian territory
32557                                  western sahara
32558    south georgia and the south sandwich islands
32559                          libyan arab jamahiriya
32560                                          serbia
Length: 32561, dtype: object

In [212]:
spi.str.strip("Pitcairn")

0                                        Cook Islands
1                                          Seychelles
2                                        Cook Islands
3                                             Saint M
4                                             Lesotho
                             ...
32556                             lestinian Territory
32557                                     Western Sah
32558    South Georgia and the South Sandwich Islands
32559                           Libyan Arab Jamahiriy
32560                                            Serb
Length: 32561, dtype: object

In [213]:
spi.str.split(' ', expand = True)

,0,1,2,3,4,5,6,7
0,Cook,Islands,None,None,None,None,None,None
1,Seychelles,None,None,None,None,None,None,None
2,Cook,Islands,None,None,None,None,None,None
3,Saint,Martin,None,None,None,None,None,None
4,Lesotho,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...
32556,Palestinian,Territory,None,None,None,None,None,None
32557,Western,Sahara,None,None,None,None,None,None
32558,South,Georgia,and,the,South,Sandwich,Islands,None
32559,Libyan,Arab,Jamahiriya,None,None,None,None,None
32560,Serbia,None,None,None,None,None,None,None

In [214]:
spi.str[0:5]

0        Cook
1        Seych
2        Cook
3        Saint
4        Lesot
         ...
32556    Pales
32557    Weste
32558    South
32559    Libya
32560    Serbi
Length: 32561, dtype: object

# Agrupamento numérico

In [215]:
serie_pais

Cook Islands                                    39
Seychelles                                      50
Cook Islands                                    38
Saint Martin                                    53
Lesotho                                         28
                                                ..
Palestinian Territory                           27
Western Sahara                                  40
South Georgia and the South Sandwich Islands    58
Libyan Arab Jamahiriya                          22
Serbia                                          52
Length: 32561, dtype: int64

In [216]:
serie_pais.sum()

np.int64(1256257)

In [217]:
serie_pais.mean()

np.float64(38.58164675532078)

In [218]:
serie_pais.median()

37.0

In [219]:
serie_pais.count()

np.int64(32561)

In [220]:
serie_pais.std()

13.640432553581146

In [221]:
serie_pais.var()

186.06140024879625

In [222]:
mb = serie_pais.loc["Brazil"].mean().round()
mi = serie_pais.loc["India"].mean().round()

print('Brasil: ', mb)
print('India: ', mi)

Brasil:  38.0
India:  40.0

In [223]:
serie_pais.quantile([0.25, 0.5, 0.75])

0.25    28.0
0.50    37.0
0.75    48.0
dtype: float64

# Agrupamento Categórico

In [224]:
spi

0                                        Cook Islands
1                                          Seychelles
2                                        Cook Islands
3                                        Saint Martin
4                                             Lesotho
                             ...
32556                           Palestinian Territory
32557                                  Western Sahara
32558    South Georgia and the South Sandwich Islands
32559                          Libyan Arab Jamahiriya
32560                                          Serbia
Length: 32561, dtype: object

In [225]:
spi.value_counts()

Korea                        267
Congo                        260
French Guiana                168
El Salvador                  162
Reunion                      158
                            ...
Georgia                      109
Bouvet Island (Bouvetoya)    109
China                        108
Solomon Islands              108
Guatemala                    107
Name: count, Length: 243, dtype: int64

In [226]:
spi.value_counts(normalize = True)

Korea                        0.008200
Congo                        0.007985
French Guiana                0.005160
El Salvador                  0.004975
Reunion                      0.004852
                               ...
Georgia                      0.003348
Bouvet Island (Bouvetoya)    0.003348
China                        0.003317
Solomon Islands              0.003317
Guatemala                    0.003286
Name: proportion, Length: 243, dtype: float64

In [227]:
spi.unique()

array(['Cook Islands', 'Seychelles', 'Saint Martin', 'Lesotho', 'Guam',
       'Costa Rica', 'Sweden', 'Colombia', 'Spain', 'Samoa',
       'Czech Republic', 'Martinique', 'Portugal', 'Tajikistan',
       'Suriname', 'Myanmar', 'Comoros', 'Slovenia', 'Cuba',
       'Sierra Leone', 'Bahrain', 'Cameroon', 'Syrian Arab Republic',
       'Cocos (Keeling) Islands', 'Pitcairn Islands', 'Gabon',
       'Kazakhstan', 'United States Virgin Islands',
       'Northern Mariana Islands', 'Saint Helena', 'Belgium', 'Grenada',
       'Egypt', 'Mali', 'Maldives', 'Estonia', 'Congo', 'Croatia',
       'Christmas Island', 'India', 'Kenya', 'Namibia',
       'Falkland Islands (Malvinas)', 'Brazil', 'Cyprus', 'Hong Kong',
       'Singapore', 'Pakistan', 'French Southern Territories',
       'Montserrat', 'Netherlands', "Cote d'Ivoire", 'Swaziland',
       'Tokelau', 'Mauritania', 'French Guiana', 'Western Sahara',
       'Denmark', 'Barbados', 'Russian Federation', 'Malawi',
       'Trinidad and Tobago', 'Korea', 'Dominican Republic',
       'Saint Pierre and Miquelon',
       'United States Minor Outlying Islands', 'Liberia',
       'Kyrgyz Republic', 'Faroe Islands', 'Sudan', 'Paraguay',
       'Luxembourg', 'Ecuador', 'Moldova', 'Montenegro', 'Georgia',
       'Ethiopia', 'Ukraine', 'United Arab Emirates', 'Vanuatu', 'Peru',
       'Fiji', 'Equatorial Guinea', 'Puerto Rico', 'Mauritius',
       'El Salvador', 'Bolivia', 'Cape Verde', 'Reunion',
       'Saint Barthelemy', 'Madagascar',
       'Heard Island and McDonald Islands', 'Thailand', 'Nepal',
       'Brunei Darussalam', 'Norway', 'Italy', 'Indonesia', 'Guinea',
       'Haiti', 'South Georgia and the South Sandwich Islands', 'Algeria',
       'Gibraltar', 'Mozambique', 'Yemen', 'Afghanistan', 'South Africa',
       'Ghana', 'Saudi Arabia', 'Nauru', 'Guatemala', 'Turkey', 'Mayotte',
       'Libyan Arab Jamahiriya', 'French Polynesia',
       'Turks and Caicos Islands', 'New Zealand', 'Oman', 'Greece',
       'Nicaragua', 'Senegal', 'Somalia', 'Marshall Islands',
       'Holy See (Vatican City State)', 'Lithuania', 'Serbia', 'Bhutan',
       'Bahamas', 'Sri Lanka', 'Jordan', 'Mongolia',
       'Saint Vincent and the Grenadines', 'France', 'Uzbekistan',
       'Bouvet Island (Bouvetoya)', 'Chad', 'Saint Kitts and Nevis',
       'American Samoa', 'Palau', 'Central African Republic', 'Bulgaria',
       'Jamaica', 'Malaysia', 'Nigeria', 'Niger', 'Poland', 'Guadeloupe',
       'Uganda', 'Botswana', 'Tuvalu', 'Azerbaijan', 'Albania', 'Benin',
       'Liechtenstein', 'Armenia', 'Isle of Man', 'Cambodia', 'Guyana',
       'Svalbard & Jan Mayen Islands', 'San Marino', 'Finland', 'Andorra',
       'Eritrea', 'Hungary', 'Belize', 'North Macedonia', 'Monaco',
       'Palestinian Territory', 'United Kingdom',
       'British Virgin Islands',
       'British Indian Ocean Territory (Chagos Archipelago)', 'Macao',
       'Germany', 'Vietnam', 'Antigua and Barbuda',
       'Antarctica (the territory South of 60 deg S)', 'Aruba',
       'Papua New Guinea', 'Greenland', 'Anguilla', 'Cayman Islands',
       'Taiwan', 'Malta', 'Philippines', 'Belarus', 'Honduras',
       'Norfolk Island', 'Switzerland', 'Panama', 'Morocco', 'Tonga',
       'Solomon Islands', 'Japan', 'Kuwait', 'Bosnia and Herzegovina',
       'Romania', 'Netherlands Antilles', 'New Caledonia', 'Angola',
       'Burundi', 'Jersey', 'Chile', 'Timor-Leste', 'Guernsey',
       'Micronesia', 'China', 'Bangladesh', 'Zimbabwe', 'Venezuela',
       'Latvia', 'Iran', 'Ireland', 'Canada', 'Sao Tome and Principe',
       'Bermuda', 'Dominica', 'Wallis and Futuna', 'Rwanda', 'Iceland',
       'Tanzania', 'Niue', 'Mexico', 'Tunisia', 'Djibouti', 'Lebanon',
       'Australia', 'Togo', 'Argentina', 'Uruguay', 'Qatar', 'Iraq',
       'Kiribati', 'Burkina Faso', 'Slovakia (Slovak Republic)',
       'United States of America', 'Guinea-Bissau', 'Turkmenistan',
       'Saint Lucia', 'Zambia', 'Israel', 'Austria',
       "Lao People's Democratic Republic", 'Gambia'], dtype=object)

In [228]:
spi.nunique()

243

# Valores faltantes

In [229]:
serie_faltante = pd.Series([
    1, 2, 3, np.nan, 5,
    6, np.nan, 8, 9, 10,
    np.nan, 12, 13, 14, np.nan,
    16, 17, 18, 19, 20,
    np.nan, 22, 23, np.nan, 25,
    26, 27, 28, np.nan, 30,
    31, 32, 33, 34, np.nan,
    36, 37, np.nan, 39, 40,
    41, 42, 43, np.nan, 45,
    46, 47, 48, 49, np.nan
])
serie_faltante

0      1.0
1      2.0
2      3.0
3      NaN
4      5.0
5      6.0
6      NaN
7      8.0
8      9.0
9     10.0
10     NaN
11    12.0
12    13.0
13    14.0
14     NaN
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20     NaN
21    22.0
22    23.0
23     NaN
24    25.0
25    26.0
26    27.0
27    28.0
28     NaN
29    30.0
30    31.0
31    32.0
32    33.0
33    34.0
34     NaN
35    36.0
36    37.0
37     NaN
38    39.0
39    40.0
40    41.0
41    42.0
42    43.0
43     NaN
44    45.0
45    46.0
46    47.0
47    48.0
48    49.0
49     NaN
dtype: float64

In [230]:
serie_faltante.isna() # Verifica se tem valores faltantes, retornando False ou True

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22    False
23     True
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33    False
34     True
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43     True
44    False
45    False
46    False
47    False
48    False
49     True
dtype: bool

In [231]:
serie_faltante.isna().sum()

np.int64(11)

In [232]:
serie_faltante.value_counts(dropna = False)

NaN     11
1.0      1
2.0      1
3.0      1
5.0      1
6.0      1
8.0      1
9.0      1
10.0     1
12.0     1
13.0     1
14.0     1
16.0     1
17.0     1
18.0     1
19.0     1
20.0     1
22.0     1
23.0     1
25.0     1
26.0     1
27.0     1
28.0     1
30.0     1
31.0     1
32.0     1
33.0     1
34.0     1
36.0     1
37.0     1
39.0     1
40.0     1
41.0     1
42.0     1
43.0     1
45.0     1
46.0     1
47.0     1
48.0     1
49.0     1
Name: count, dtype: int64

In [233]:
serie_faltante.fillna(0)

0      1.0
1      2.0
2      3.0
3      0.0
4      5.0
5      6.0
6      0.0
7      8.0
8      9.0
9     10.0
10     0.0
11    12.0
12    13.0
13    14.0
14     0.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20     0.0
21    22.0
22    23.0
23     0.0
24    25.0
25    26.0
26    27.0
27    28.0
28     0.0
29    30.0
30    31.0
31    32.0
32    33.0
33    34.0
34     0.0
35    36.0
36    37.0
37     0.0
38    39.0
39    40.0
40    41.0
41    42.0
42    43.0
43     0.0
44    45.0
45    46.0
46    47.0
47    48.0
48    49.0
49     0.0
dtype: float64

In [234]:
serie_faltante.dropna()

0      1.0
1      2.0
2      3.0
4      5.0
5      6.0
7      8.0
8      9.0
9     10.0
11    12.0
12    13.0
13    14.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
21    22.0
22    23.0
24    25.0
25    26.0
26    27.0
27    28.0
29    30.0
30    31.0
31    32.0
32    33.0
33    34.0
35    36.0
36    37.0
38    39.0
39    40.0
40    41.0
41    42.0
42    43.0
44    45.0
45    46.0
46    47.0
47    48.0
48    49.0
dtype: float64

In [235]:
serie_faltante.fillna(serie_faltante.mean()).round()

0      1.0
1      2.0
2      3.0
3     26.0
4      5.0
5      6.0
6     26.0
7      8.0
8      9.0
9     10.0
10    26.0
11    12.0
12    13.0
13    14.0
14    26.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20    26.0
21    22.0
22    23.0
23    26.0
24    25.0
25    26.0
26    27.0
27    28.0
28    26.0
29    30.0
30    31.0
31    32.0
32    33.0
33    34.0
34    26.0
35    36.0
36    37.0
37    26.0
38    39.0
39    40.0
40    41.0
41    42.0
42    43.0
43    26.0
44    45.0
45    46.0
46    47.0
47    48.0
48    49.0
49    26.0
dtype: float64

In [236]:
serie_faltante = pd.Series(["Maça","Banana","Arroz","Arroz", np.nan,"Batata"])
serie_faltante

0      Maça
1    Banana
2     Arroz
3     Arroz
4       NaN
5    Batata
dtype: object

In [237]:
serie_faltante.isna().sum()

np.int64(1)

In [238]:
serie_faltante.fillna("Não informado")

0             Maça
1           Banana
2            Arroz
3            Arroz
4    Não informado
5           Batata
dtype: object

In [239]:
serie_faltante.mode().iloc[0] # Retorna o valor que mais aparece

'Arroz'

In [240]:
serie_faltante.fillna(serie_faltante.mode().iloc[0])

0      Maça
1    Banana
2     Arroz
3     Arroz
4     Arroz
5    Batata
dtype: object

# Funções

In [241]:
serie_idade

0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, Length: 32561, dtype: int64

In [242]:
serie_idade.loc[serie_idade < 18]

106      17
209      17
262      17
271      17
335      17
         ..
31772    17
31864    17
31959    17
32282    17
32447    17
Name: age, Length: 395, dtype: int64

In [243]:
# Criando uma função
def corrige_idade(idade):
    if idade < 18:
        idade = 18
    return idade

In [244]:
# Aplicando uma função para todas os registros que atendam
si = serie_idade.apply(corrige_idade)

In [245]:
si.loc[serie_idade < 18]

106      18
209      18
262      18
271      18
335      18
         ..
31772    18
31864    18
31959    18
32282    18
32447    18
Name: age, Length: 395, dtype: int64

In [246]:
serie_idade = serie_idade.apply(lambda x: 17 if x == 18 else x)

In [247]:
serie_idade.loc[serie_idade < 18]

51       17
78       17
80       17
106      17
168      17
         ..
32345    17
32392    17
32443    17
32447    17
32496    17
Name: age, Length: 945, dtype: int64

In [248]:
serie_idade2 = serie_idade.iloc[0:6]

In [249]:
serie_idade2

0    39
1    50
2    38
3    53
4    28
5    37
Name: age, dtype: int64

In [250]:
serie_idade2.where(serie_idade2 < 40, 0)

0    39
1     0
2    38
3     0
4    28
5    37
Name: age, dtype: int64

# Dataframe

## Criação do Dataframe

In [251]:
# Lista com duas dimensões
data = [
    ['Alice', 25, 'São Paulo'],
    ['João', 30, 'Rio de Janeiro'],
    ['Bruno', 35, 'Curitiba'],
    ['Carlos', 40, 'Manaus']
]

In [252]:
type(data)

list

In [253]:
colunas = ['Nome', 'Idade', 'Cidade']

In [254]:
df = pd.DataFrame(data, columns=colunas)
df

     Nome  Idade          Cidade
0   Alice     25       São Paulo
1    João     30  Rio de Janeiro
2   Bruno     35        Curitiba
3  Carlos     40          Manaus

In [255]:
# Utilizando dicionarios
dataDict = {'Nome': ['Alice', 'João', 'Bruno', 'Carlos'],
        'Idade': [25, 30, 40, 50],
        'Cidade': ['São Paulo', 'Rio de Janeiro', 'Curitiba', 'Manaus']}

In [256]:
type(dataDict)

dict

In [257]:
df = pd.DataFrame(dataDict)
df

     Nome  Idade          Cidade
0   Alice     25       São Paulo
1    João     30  Rio de Janeiro
2   Bruno     40        Curitiba
3  Carlos     50          Manaus

In [258]:
data = np.array([
    ['Alice', 25, 'São Paulo'],
    ['João', 30, 'Rio de Janeiro'],
    ['Bruno', 35, 'Curitiba'],
    ['Carlos', 40, 'Manaus']])

type(data)

numpy.ndarray

In [259]:
data

array([['Alice', '25', 'São Paulo'],
       ['João', '30', 'Rio de Janeiro'],
       ['Bruno', '35', 'Curitiba'],
       ['Carlos', '40', 'Manaus']], dtype='<U21')

In [260]:
df = pd.DataFrame(data, columns = colunas)
df

     Nome Idade          Cidade
0   Alice    25       São Paulo
1    João    30  Rio de Janeiro
2   Bruno    35        Curitiba
3  Carlos    40          Manaus

In [261]:
# Lista de tuplas
data = [('Alice', 25, 'São Paulo'),
        ('João', 30, 'Rio de Janeiro'),
        ('Bruno', 35, 'Curitiba'),
        ('Carlos', 40, 'Manaus')]

In [262]:
type(data), type(data[0])

(list, tuple)

In [263]:
data

[('Alice', 25, 'São Paulo'),
 ('João', 30, 'Rio de Janeiro'),
 ('Bruno', 35, 'Curitiba'),
 ('Carlos', 40, 'Manaus')]

In [264]:
#
df = pd.DataFrame(data, columns = colunas)
df

     Nome  Idade          Cidade
0   Alice     25       São Paulo
1    João     30  Rio de Janeiro
2   Bruno     35        Curitiba
3  Carlos     40          Manaus

In [265]:
# Utilizando dicionarios
data = {'Nome': pd.Series(['Alice', 'João', 'Bruno', 'Carlos']),
        'Idade': pd.Series([25, 30, 40, 50]),
        'Cidade': pd.Series(['São Paulo', 'Rio de Janeiro', 'Curitiba', 'Manaus'])}
data

{'Nome': 0     Alice
 1      João
 2     Bruno
 3    Carlos
 dtype: object,
 'Idade': 0    25
 1    30
 2    40
 3    50
 dtype: int64,
 'Cidade': 0         São Paulo
 1    Rio de Janeiro
 2          Curitiba
 3            Manaus
 dtype: object}

In [266]:
type(data)

dict

In [267]:
df = pd.DataFrame(data)
df

     Nome  Idade          Cidade
0   Alice     25       São Paulo
1    João     30  Rio de Janeiro
2   Bruno     40        Curitiba
3  Carlos     50          Manaus

In [268]:
# Utilizando dicionarios
data = {'Nome': np.array(['Alice', 'João', 'Bruno', 'Carlos']),
        'Idade': np.array([25, 30, 40, 50]),
        'Cidade': np.array(['São Paulo', 'Rio de Janeiro', 'Curitiba', 'Manaus'])}
data

{'Nome': array(['Alice', 'João', 'Bruno', 'Carlos'], dtype='<U6'),
 'Idade': array([25, 30, 40, 50]),
 'Cidade': array(['São Paulo', 'Rio de Janeiro', 'Curitiba', 'Manaus'], dtype='<U14')}

In [269]:
type(data)

dict

In [270]:
df = pd.DataFrame(data)
df

     Nome  Idade          Cidade
0   Alice     25       São Paulo
1    João     30  Rio de Janeiro
2   Bruno     40        Curitiba
3  Carlos     50          Manaus